import type { SubtitleStyle } from '../types/subtitle';

export const SUBTITLE_PRESETS: SubtitleStyle[] = [
  {
    id: 'hormozi-bold',
    name: 'Hormozi Viral',
    fontFamily: 'Montserrat',
    fontSize: 42,
    textColor: '#FFFFFF',
    highlightColor: '#FFE500',
    secondaryHighlightColor: '#22C55E',
    textTransform: 'uppercase',
    fontWeight: 900,
    hasStroke: true,
    strokeColor: '#000000',
    strokeWidth: 4,
    hasBackground: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPadding: 8,
    borderRadius: 8,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.9)',
    shadowBlur: 8,
    shadowOffsetX: 3,
    shadowOffsetY: 3,
    positionY: 72,
    positionX: 50,
    maxWidth: 90,
    displayMode: 'two-words',
    animation: 'pop',
    animationScale: 1.22,
    rotateActiveWord: true,
    activeWordAngle: -3,
    showEmojis: true,
  },
  {
    id: 'mrbeast-glow',
    name: 'MrBeast Energy',
    fontFamily: 'Anton',
    fontSize: 48,
    textColor: '#FFFFFF',
    highlightColor: '#00FF66',
    secondaryHighlightColor: '#FF0055',
    textTransform: 'uppercase',
    fontWeight: 900,
    hasStroke: true,
    strokeColor: '#000000',
    strokeWidth: 5,
    hasBackground: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.7,
    backgroundPadding: 10,
    borderRadius: 12,
    hasShadow: true,
    shadowColor: '#00FF66',
    shadowBlur: 16,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    positionY: 68,
    positionX: 50,
    maxWidth: 85,
    displayMode: 'one-word',
    animation: 'bounce',
    animationScale: 1.3,
    rotateActiveWord: true,
    activeWordAngle: 4,
    showEmojis: true,
  },
  {
    id: 'cyberpunk-neon',
    name: 'Cyberpunk Neon',
    fontFamily: 'Bebas Neue',
    fontSize: 46,
    textColor: '#38BDF8',
    highlightColor: '#F43F5E',
    secondaryHighlightColor: '#FBBF24',
    textTransform: 'uppercase',
    fontWeight: 800,
    hasStroke: true,
    strokeColor: '#090A0F',
    strokeWidth: 3,
    hasBackground: true,
    backgroundColor: '#070A14',
    backgroundOpacity: 0.85,
    backgroundPadding: 12,
    borderRadius: 10,
    hasShadow: true,
    shadowColor: '#F43F5E',
    shadowBlur: 20,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    positionY: 75,
    positionX: 50,
    maxWidth: 85,
    displayMode: 'two-words',
    animation: 'glow',
    animationScale: 1.15,
    rotateActiveWord: false,
    activeWordAngle: 0,
    showEmojis: true,
  },
  {
    id: 'minimal-pill',
    name: 'Clean Minimalist',
    fontFamily: 'Outfit',
    fontSize: 34,
    textColor: '#F8FAFC',
    highlightColor: '#60A5FA',
    textTransform: 'none',
    fontWeight: 800,
    hasStroke: false,
    strokeColor: '#000000',
    strokeWidth: 0,
    hasBackground: true,
    backgroundColor: '#0F172A',
    backgroundOpacity: 0.8,
    backgroundPadding: 10,
    borderRadius: 24,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.4)',
    shadowBlur: 12,
    shadowOffsetX: 0,
    shadowOffsetY: 4,
    positionY: 80,
    positionX: 50,
    maxWidth: 90,
    displayMode: 'three-words',
    animation: 'pop',
    animationScale: 1.1,
    rotateActiveWord: false,
    activeWordAngle: 0,
    showEmojis: false,
  },
  {
    id: 'comic-pop',
    name: 'Cartoon Punch',
    fontFamily: 'Titan One',
    fontSize: 40,
    textColor: '#FFFFFF',
    highlightColor: '#FB923C',
    textTransform: 'uppercase',
    fontWeight: 900,
    hasStroke: true,
    strokeColor: '#1E293B',
    strokeWidth: 4,
    hasBackground: false,
    backgroundColor: '#000000',
    backgroundOpacity: 0.6,
    backgroundPadding: 8,
    borderRadius: 8,
    hasShadow: true,
    shadowColor: 'rgba(0, 0, 0, 0.8)',
    shadowBlur: 6,
    shadowOffsetX: 3,
    shadowOffsetY: 3,
    positionY: 70,
    positionX: 50,
    maxWidth: 85,
    displayMode: 'two-words',
    animation: 'bounce',
    animationScale: 1.25,
    rotateActiveWord: true,
    activeWordAngle: -4,
    showEmojis: true,
  },
  {
    id: 'karaoke-classic',
    name: 'Karaoke Pro',
    fontFamily: 'Poppins',
    fontSize: 36,
    textColor: 'rgba(255, 255, 255, 0.6)',
    highlightColor: '#A855F7',
    textTransform: 'capitalize',
    fontWeight: 900,
    hasStroke: true,
    strokeColor: '#000000',
    strokeWidth: 3,
    hasBackground: true,
    backgroundColor: '#000000',
    backgroundOpacity: 0.6,
    backgroundPadding: 8,
    borderRadius: 12,
    hasShadow: false,
    shadowColor: '#000000',
    shadowBlur: 0,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    positionY: 76,
    positionX: 50,
    maxWidth: 90,
    displayMode: 'full-line',
    animation: 'glow',
    animationScale: 1.12,
    rotateActiveWord: false,
    activeWordAngle: 0,
    showEmojis: false,
  }
];

export const AVAILABLE_FONTS = [
  { name: 'Montserrat (Ultra Bold)', value: 'Montserrat' },
  { name: 'Anton (Impact Heavy)', value: 'Anton' },
  { name: 'Outfit (Modern Tech)', value: 'Outfit' },
  { name: 'Poppins (Smooth & Clean)', value: 'Poppins' },
  { name: 'Bebas Neue (Tall & Punchy)', value: 'Bebas Neue' },
  { name: 'Rubik (Heavy Rounded)', value: 'Rubik' },
  { name: 'Titan One (Fun & Punch)', value: 'Titan One' },
  { name: 'Bungee (Retro Arcade)', value: 'Bungee' },
];
